### ISSUE TITLE
[Docs] Need guide for css-modules

### ISSUE THREAD

**Issue by retyui** [ai/webp-in-css#13]
## The problem 

When you enable `cssModules: true` options in your config `css-loader`

You get the next result:
```css
body.no-webp__2343 .CollectriumSection_root__022e {
  background: url(/_next/static/images/bg_collectrium-246049879ed73fd9d55f106344d77c0b.jpg) 100% / cover fixed no-repeat;
}

body.webp__2d34 .CollectriumSection_root__022e {
  background: url(/_next/static/images/bg_collectrium-820955af9a57e6011b9180e00965b883.webp) 100% / cover fixed no-repeat;
}
```

To fix that I passed custom `getLocalIdent` function:
```js
const getLocalIdent = require('css-loader/lib/getLocalIdent');

const cssLoaderOptions = {
  localIdentName: isProd ? '[hash:5]' : '[folder]_[local]__[hash:4]',
  getLocalIdent: (
    loaderContext,
    localIdentName,
    localName,
    options,
  ) => {
    if (localName.includes('webp')) {
      return localName;
    }

    return getLocalIdent(
      loaderContext,
      localIdentName,
      localName,
      options,
    );
  },
}
```

Would be great to create a section **Know Issues** and add this case there
