### ISSUE TITLE
AddClass doesn't handle case of class already starting with "body"

### ISSUE THREAD

**Issue by dmnsgn** [ai/webp-in-css#30]
Source code only handles `html`:

https://github.com/ai/webp-in-css/blob/e62a00e9bd1996efcd5f2ca154d31d14eb6dd871/plugin.js#L22-L26

The following:
```css
body main {
  background-image: url(./assets/test.jpeg);
  background-size: contain;
}
```
will generate:
```css
body.webp body main {
  background-image: url(/assets/test.0e61a19d72e86eea12e0.webp);
}
```
